#!/bin/bash
# build.sh — compile NextMeeting.swift into a menu bar .app bundle.
#
# No Xcode project, and no Xcode. `swiftc` ships with the Command Line Tools, and this app needs
# nothing a project file would give it: no asset catalogue, no storyboard, and — because it reads a
# JSON file instead of talking to EventKit — no entitlements and no macOS permission prompt.
#
# That last point is also why the ad-hoc signature below is harmless: macOS keys calendar and
# contacts access to the signing identity, so a bundle that never asks for either never gets
# re-prompted when the signature changes between builds.
#
# Output:  menubar/build/NextMeeting.app   (gitignored)
#
# Usage:
#   bash menubar/build.sh            # build
#   bash menubar/build.sh --run      # build, then relaunch it
#   bash menubar/build.sh --install  # build, copy to ~/Applications, start at login

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$HERE/.." && pwd)"
BUILD="$HERE/build"
APP="$BUILD/NextMeeting.app"
CONTENTS="$APP/Contents"
BUNDLE_ID="io.llinkas.meeting-notification-bar"
LABEL="$BUNDLE_ID.menubar"

RUN=0
INSTALL=0
for a in "$@"; do
  case "$a" in
    --run)     RUN=1 ;;
    --install) INSTALL=1 ;;
    *) echo "unknown flag: $a" >&2; exit 2 ;;
  esac
done

command -v swiftc >/dev/null || {
  echo "swiftc not found. Install the Command Line Tools:  xcode-select --install" >&2
  exit 1
}

echo "==> building $APP"
rm -rf "$APP"
mkdir -p "$CONTENTS/MacOS" "$CONTENTS/Resources"

# LSUIElement is the one non-negotiable key: without it the app takes a Dock icon and appears in the
# app switcher, which is wrong for something that only ever draws in the menu bar.
cat >"$CONTENTS/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key>              <string>NextMeeting</string>
  <key>CFBundleDisplayName</key>       <string>Next Meeting</string>
  <key>CFBundleIdentifier</key>        <string>$BUNDLE_ID</string>
  <key>CFBundleExecutable</key>        <string>NextMeeting</string>
  <key>CFBundlePackageType</key>       <string>APPL</string>
  <key>CFBundleShortVersionString</key><string>1.0</string>
  <key>CFBundleVersion</key>           <string>1</string>
  <key>LSMinimumSystemVersion</key>    <string>13.0</string>
  <key>LSUIElement</key>               <true/>
  <key>NSHighResolutionCapable</key>   <true/>
</dict>
</plist>
PLIST

# -parse-as-library is required, not optional: a single file handed to swiftc is otherwise treated as
# top-level code, and @main is rejected in a module that has any.
swiftc -O -parse-as-library \
  -target "$(uname -m)-apple-macosx13.0" \
  -framework AppKit -framework SwiftUI \
  -o "$CONTENTS/MacOS/NextMeeting" \
  "$HERE/NextMeeting.swift"

# The app finds this via Bundle.main.url(forResource:) and runs it with /bin/bash.
#
# It is a shim, not a copy. The real script needs the checkout to find bin/fetch-events.js and the
# OAuth token, and it cannot derive that by walking up from inside the bundle. Stamping the absolute
# path in here also means editing refresh-events.sh takes effect without a rebuild.
[ -d "$REPO/.secrets" ] || {
  echo "   note: no $REPO/.secrets yet — before this can show anything, run:" >&2
  echo "         node bin/auth.js --login" >&2
}
cat >"$CONTENTS/Resources/refresh-events.sh" <<SHIM
#!/bin/bash
# Generated by build.sh — do not edit. Points back at the checkout it was built from.
export MNB_HOME="\${MNB_HOME:-$REPO}"
exec /bin/bash "\$MNB_HOME/menubar/refresh-events.sh" "\$@"
SHIM
chmod +x "$CONTENTS/Resources/refresh-events.sh"

# Ad-hoc signature. Enough for Gatekeeper to run a locally built app; see the note at the top of this
# file for why the unstable identity costs nothing here.
codesign --force --deep --sign - "$APP" >/dev/null 2>&1 || \
  echo "   (codesign failed; the app will still run locally)"

echo "==> built $APP"

if [ "$INSTALL" = 1 ]; then
  DEST="$HOME/Applications"
  mkdir -p "$DEST"

  # Another checkout may already own this path. The bundle identifiers differ, so both LaunchAgents
  # would survive `bootstrap` and then fight over one binary — and whichever built last wins,
  # silently. Refuse rather than clobber.
  if [ -d "$DEST/NextMeeting.app" ]; then
    EXISTING_ID="$(/usr/libexec/PlistBuddy -c 'Print :CFBundleIdentifier' "$DEST/NextMeeting.app/Contents/Info.plist" 2>/dev/null || echo '')"
    if [ -n "$EXISTING_ID" ] && [ "$EXISTING_ID" != "$BUNDLE_ID" ]; then
      # Find the LaunchAgent that actually points at this path instead of deriving its label from
      # the bundle id. Those are not the same string: a bundle id may already end in `.menubar`, and
      # appending another `.menubar` yields a label that matches nothing. Following instructions
      # built that way is worse than having none — the bootout and the rm both no-op, the third
      # command deletes the app regardless, and launchd is left loaded against a missing binary.
      OTHER_LABEL=""
      for p in "$HOME/Library/LaunchAgents"/*.plist; do
        [ -e "$p" ] || continue
        if /usr/libexec/PlistBuddy -c 'Print :ProgramArguments' "$p" 2>/dev/null \
             | grep -qF "$DEST/NextMeeting.app"; then
          OTHER_LABEL="$(basename "$p" .plist)"
          break
        fi
      done

      echo "" >&2
      echo "   REFUSING TO INSTALL: $DEST/NextMeeting.app already belongs to $EXISTING_ID." >&2
      echo "   Two apps at one path with two LaunchAgents will fight. Remove the other one first:" >&2
      if [ -n "$OTHER_LABEL" ]; then
        echo "       launchctl bootout \"gui/\$UID/$OTHER_LABEL\"" >&2
        echo "       rm -f ~/Library/LaunchAgents/$OTHER_LABEL.plist" >&2
      else
        echo "       # no LaunchAgent references that path; check by hand:" >&2
        echo "       grep -l NextMeeting ~/Library/LaunchAgents/*.plist" >&2
      fi
      echo "       rm -rf $DEST/NextMeeting.app" >&2
      echo "" >&2
      exit 1
    fi
  fi
  pkill -f "NextMeeting.app/Contents/MacOS/NextMeeting" 2>/dev/null || true
  rm -rf "$DEST/NextMeeting.app"
  cp -R "$APP" "$DEST/NextMeeting.app"
  echo "==> installed $DEST/NextMeeting.app"

  PLIST_PATH="$HOME/Library/LaunchAgents/$LABEL.plist"
  mkdir -p "$HOME/Library/LaunchAgents" "$HOME/Library/Logs/meeting-notification-bar"
  cat >"$PLIST_PATH" <<AGENT
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>$LABEL</string>
  <key>ProgramArguments</key>
  <array>
    <string>$DEST/NextMeeting.app/Contents/MacOS/NextMeeting</string>
  </array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><false/>
  <key>StandardErrorPath</key><string>$HOME/Library/Logs/meeting-notification-bar/menubar.launchd.log</string>
</dict>
</plist>
AGENT
  launchctl bootout "gui/$UID/$LABEL" 2>/dev/null || true
  launchctl bootstrap "gui/$UID" "$PLIST_PATH"
  echo "==> starts at login ($PLIST_PATH)"
  echo "==> running now — look at the right end of your menu bar"
  exit 0
fi

if [ "$RUN" = 1 ]; then
  pkill -f "NextMeeting.app/Contents/MacOS/NextMeeting" 2>/dev/null || true
  sleep 0.3
  open "$APP"
  echo "==> launched (look at the right end of your menu bar)"
fi
